-- MinesMinis Decodable Stories Seed Data
-- Generated from generatedStories.ts (50 stories, groups 1-5)
-- Run this against the stories_decodable table

INSERT INTO stories_decodable (
  id, title, title_tr, phonics_group, topic, mascot_id,
  scenes, word_count, decodability_score,
  comprehension_question, comprehension_question_tr,
  comprehension_answers, comprehension_answers_tr,
  correct_answer_index, sort_order
)
VALUES
  (
    'story-g1-001',
    'Sat and Pat',
    'Sat ve Pat',
    1,
    'friends',
    'mimi',
    '[{"text":"Pat sat on a tin. Nat sat on a pin.","textTr":"Pat bir tenekenin üzerine oturdu. Nat bir iğnenin üzerine oturdu.","highlightedWords":[],"location":"home"},{"text":"Nat sat up. Nat can spin and spin!","textTr":"Nat kalktı. Nat dönebilir ve dönebilir!","highlightedWords":[],"location":"home"},{"text":"Pat and Nat sat in the pit. It is tan.","textTr":"Pat ve Nat çukurda oturdu. Tenrengi renkteydi.","highlightedWords":[],"location":"garden"}]'::jsonb,
    28,
    90,
    'What did Pat sit on?',
    'Pat neyin üzerine oturdu?',
    ARRAY['A tin', 'A pit', 'A pin'],
    ARRAY['Bir tenekenin üzerine', 'Bir çukura', 'Bir iğnenin üzerine'],
    0,
    1
  ),
  (
    'story-g1-002',
    'The Tin Can',
    'Teneke Kutu',
    1,
    'adventure',
    'mimi',
    '[{"text":"I can tap the tin. Tap, tap, tap!","textTr":"Tenekeye dokunabilirim. Dokun, dokun, dokun!","highlightedWords":[],"location":"home"},{"text":"It is a pan. I sat on it.","textTr":"Bu bir tava. Üzerine oturdum.","highlightedWords":[],"location":"home"},{"text":"I can snap! It is in the pan. It is a tip.","textTr":"Çıtlatabiliyorum! Tavada. Bu bir uç.","highlightedWords":[],"location":"kitchen"}]'::jsonb,
    28,
    90,
    'What is in the pan?',
    'Tavada ne var?',
    ARRAY['A tip', 'A pin', 'A nap'],
    ARRAY['Bir uç', 'Bir iğne', 'Bir şekerleme'],
    0,
    2
  ),
  (
    'story-g1-003',
    'Tip the Cat',
    'Tip Adlı Kedi',
    1,
    'animals',
    'mimi',
    '[{"text":"Tip is a tan cat. Tip sat in the pit.","textTr":"Tip, ten renkli bir kedidir. Tip çukurda oturdu.","highlightedWords":[],"location":"garden"},{"text":"Tip can nip and tap. Tip can spin!","textTr":"Tip çimdikleyebilir ve dokunabilir. Tip dönebilir!","highlightedWords":[],"location":"garden"},{"text":"Tip sat on the tin. I pat Tip.","textTr":"Tip tenekenin üzerine oturdu. Tip''i okşadım.","highlightedWords":[],"location":"home"}]'::jsonb,
    26,
    91,
    'What color is Tip?',
    'Tip ne renktir?',
    ARRAY['Tan', 'Nit', 'Tip'],
    ARRAY['Ten rengi', 'Bit yumurtası', 'Uç'],
    0,
    3
  ),
  (
    'story-g1-004',
    'Sam and Nan',
    'Sam ve Nan',
    1,
    'friends',
    'mimi',
    '[{"text":"Sam sat at the pan. Nan sat at the tin.","textTr":"Sam tavanın yanına oturdu. Nan tenekenin yanına oturdu.","highlightedWords":[],"location":"kitchen"},{"text":"Sam can tap it. Nan can sip.","textTr":"Sam ona dokunabilir. Nan yudum alabilir.","highlightedWords":[],"location":"kitchen"},{"text":"Nan sat in the pit. Sam sat on a pin!","textTr":"Nan çukurda oturdu. Sam bir iğnenin üzerine oturdu!","highlightedWords":[],"location":"garden"}]'::jsonb,
    27,
    90,
    'Where did Nan sit?',
    'Nan nerede oturdu?',
    ARRAY['In the pit', 'On a tin', 'On a pan'],
    ARRAY['Çukurda', 'Tenekenin üzerinde', 'Tavanın üzerinde'],
    0,
    4
  ),
  (
    'story-g1-005',
    'Pip the Pup',
    'Pip Adlı Yavru Köpek',
    1,
    'animals',
    'mimi',
    '[{"text":"Pip is a pup. Pip sat on a pat.","textTr":"Pip bir yavru köpektir. Pip okşama üzerine oturdu.","highlightedWords":[],"location":"home"},{"text":"Pip can nip. Pip can spin and snap!","textTr":"Pip çimdikleyebilir. Pip dönebilir ve çıtlatabilir!","highlightedWords":[],"location":"garden"},{"text":"I sat and I pat Pip. Pip sat on me.","textTr":"Oturdum ve Pip''i okşadım. Pip üzerime oturdu.","highlightedWords":[],"location":"home"}]'::jsonb,
    27,
    90,
    'What can Pip do?',
    'Pip ne yapabilir?',
    ARRAY['Spin and snap', 'Sip and sit', 'Pat and tap'],
    ARRAY['Dönebilir ve çıtlatabilir', 'Yudum alabilir ve oturabilir', 'Okşayabilir ve dokunabilir'],
    0,
    5
  ),
  (
    'story-g1-006',
    'Nap at the Pit',
    'Çukurda Şekerleme',
    1,
    'nature',
    'mimi',
    '[{"text":"I sat at the pit. I sat and sat.","textTr":"Çukurun yanına oturdum. Oturdum ve oturdum.","highlightedWords":[],"location":"garden"},{"text":"I can nap in it! I nap, nap, nap.","textTr":"İçinde şekerleme yapabilirim! Uyudum, uyudum, uyudum.","highlightedWords":[],"location":"garden"},{"text":"An ant sat on a pin. It sat in the tan pit.","textTr":"Bir karınca iğnenin üzerine oturdu. Ten renkli çukurda oturdu.","highlightedWords":[],"location":"garden"}]'::jsonb,
    30,
    92,
    'Where did the ant sit?',
    'Karınca nerede oturdu?',
    ARRAY['On a pin', 'On a tin', 'In a pan'],
    ARRAY['İğnenin üzerinde', 'Tenekenin üzerinde', 'Tavada'],
    0,
    6
  ),
  (
    'story-g1-007',
    'Spin and Snap',
    'Dön ve Çıtlat',
    1,
    'play',
    'mimi',
    '[{"text":"I can spin! I spin, spin, spin.","textTr":"Dönebiliyorum! Döndüm, döndüm, döndüm.","highlightedWords":[],"location":"classroom"},{"text":"Pat can snap. Snap, snap, snap!","textTr":"Pat çıtlatabilir. Çıtlat, çıtlat, çıtlat!","highlightedWords":[],"location":"classroom"},{"text":"We sat and it is a tip. I tap it.","textTr":"Oturduk ve bu bir uç. Ona dokunuyorum.","highlightedWords":[],"location":"classroom"}]'::jsonb,
    23,
    91,
    'What can Pat do?',
    'Pat ne yapabilir?',
    ARRAY['Snap', 'Spin', 'Sip'],
    ARRAY['Çıtlatabilir', 'Dönebilir', 'Yudum alabilir'],
    0,
    7
  ),
  (
    'story-g1-008',
    'The Ant and the Pin',
    'Karınca ve İğne',
    1,
    'nature',
    'mimi',
    '[{"text":"An ant sat on a pin. It is a nut.","textTr":"Bir karınca iğnenin üzerine oturdu. Bu bir fındıktır.","highlightedWords":[],"location":"garden"},{"text":"The ant can nip. The ant sat in the pit.","textTr":"Karınca çimdikleyebilir. Karınca çukurda oturdu.","highlightedWords":[],"location":"garden"},{"text":"I tap the pin. The ant sat on it. It is tan.","textTr":"İğneye dokunuyorum. Karınca onun üzerine oturdu. Ten rengi.","highlightedWords":[],"location":"garden"}]'::jsonb,
    32,
    91,
    'Where did the ant sit first?',
    'Karınca ilk nerede oturdu?',
    ARRAY['On a pin', 'In a pit', 'On a pan'],
    ARRAY['İğnenin üzerinde', 'Çukurda', 'Tavanın üzerinde'],
    0,
    8
  ),
  (
    'story-g1-009',
    'Sip, Sip, Sip',
    'Yudum, Yudum, Yudum',
    1,
    'daily life',
    'mimi',
    '[{"text":"I sit and I sip. I sip, sip, sip.","textTr":"Oturuyorum ve yudum alıyorum. Yudum alıyorum, alıyorum, alıyorum.","highlightedWords":[],"location":"kitchen"},{"text":"It is in a tin. I tap the tin.","textTr":"Bir tenekede. Tenekeye dokunuyorum.","highlightedWords":[],"location":"kitchen"},{"text":"I sat at a pan. I sip it. It is tan.","textTr":"Tavanın yanına oturdum. Ondan yudum alıyorum. Ten rengi.","highlightedWords":[],"location":"kitchen"}]'::jsonb,
    29,
    92,
    'Where is the drink?',
    'İçecek nerede?',
    ARRAY['In a tin', 'In a pit', 'On a pin'],
    ARRAY['Bir tenekede', 'Bir çukurda', 'Bir iğnede'],
    0,
    9
  ),
  (
    'story-g1-010',
    'The Tan Ant',
    'Ten Renkli Karınca',
    1,
    'nature',
    'mimi',
    '[{"text":"A tan ant sat in a pan. I sat and sat.","textTr":"Ten renkli bir karınca tavada oturdu. Oturdum ve oturdum.","highlightedWords":[],"location":"garden"},{"text":"The ant sat on a tin tip. It can tap.","textTr":"Karınca teneke ucun üzerine oturdu. Dokunabilir.","highlightedWords":[],"location":"garden"},{"text":"I pat the ant. It sat on my pin. It is a nut!","textTr":"Karıncayı okşadım. İğnemin üzerine oturdu. Bu bir fındık!","highlightedWords":[],"location":"garden"}]'::jsonb,
    34,
    91,
    'What color is the ant?',
    'Karınca ne renktir?',
    ARRAY['Tan', 'Red', 'Big'],
    ARRAY['Ten rengi', 'Kırmızı', 'Büyük'],
    0,
    10
  ),
  (
    'story-g2-001',
    'The Red Hen',
    'Kırmızı Tavuk',
    2,
    'animals',
    'mimi',
    '[{"text":"A red hen sat on a mat. She met a cat.","textTr":"Kırmızı bir tavuk bir paspasın üzerine oturdu. Bir kediyle tanıştı.","highlightedWords":[],"location":"farm"},{"text":"The cat hid in a den. The hen ran.","textTr":"Kedi inde saklandı. Tavuk koştu.","highlightedWords":[],"location":"farm"},{"text":"The hen had a map. She sat and had a nap.","textTr":"Tavuğun bir haritası vardı. Oturdu ve şekerleme yaptı.","highlightedWords":[],"location":"farm"}]'::jsonb,
    31,
    88,
    'Where did the cat hide?',
    'Kedi nerede saklandı?',
    ARRAY['In a den', 'In a pan', 'On a mat'],
    ARRAY['İnde', 'Tavada', 'Paspasta'],
    0,
    11
  ),
  (
    'story-g2-002',
    'Dan the Ram',
    'Dan Adlı Koç',
    2,
    'animals',
    'mimi',
    '[{"text":"Dan is a red ram. He ran on the mat.","textTr":"Dan kırmızı bir koçtur. Paspas üzerinde koştu.","highlightedWords":[],"location":"farm"},{"text":"Dad met Dan. Dad sat on a mat.","textTr":"Baba Dan ile tanıştı. Baba bir paspas üzerine oturdu.","highlightedWords":[],"location":"farm"},{"text":"Dan ran to the den. He hid in it.","textTr":"Dan ine doğru koştu. İçinde saklandı.","highlightedWords":[],"location":"farm"}]'::jsonb,
    27,
    88,
    'Where did Dan hide?',
    'Dan nerede saklandı?',
    ARRAY['In the den', 'On the mat', 'In the pan'],
    ARRAY['İnde', 'Paspasta', 'Tavada'],
    0,
    12
  ),
  (
    'story-g2-003',
    'Meg and Her Cat',
    'Meg ve Kedisi',
    2,
    'animals',
    'mimi',
    '[{"text":"Meg met a cat. The cat sat on her map.","textTr":"Meg bir kediyle karşılaştı. Kedi onun haritasının üzerine oturdu.","highlightedWords":[],"location":"home"},{"text":"Meg had a red cap. The cat hid the cap.","textTr":"Meg''in kırmızı bir kasketi vardı. Kedi kasketi sakladı.","highlightedWords":[],"location":"home"},{"text":"Meg ran and ran. She met the cat at the mat.","textTr":"Meg koştu ve koştu. Paspasta kediyle karşılaştı.","highlightedWords":[],"location":"home"}]'::jsonb,
    31,
    87,
    'What did the cat hide?',
    'Kedi neyi sakladı?',
    ARRAY['The cap', 'The map', 'The mat'],
    ARRAY['Kasketi', 'Haritayı', 'Paspası'],
    0,
    13
  ),
  (
    'story-g2-004',
    'Ham in a Can',
    'Kutudaki Jambon',
    2,
    'food',
    'mimi',
    '[{"text":"Dad had a can. He set it on the mat.","textTr":"Babanın bir kutusu vardı. Onu paspasın üzerine koydu.","highlightedWords":[],"location":"kitchen"},{"text":"The can had ham in it. It is red.","textTr":"Kutunun içinde jambon vardı. Kırmızıydı.","highlightedWords":[],"location":"kitchen"},{"text":"I dip a pin in it. I sat and had a nap.","textTr":"Bir iğneyi içine daldırdım. Oturdum ve şekerleme yaptım.","highlightedWords":[],"location":"kitchen"}]'::jsonb,
    31,
    88,
    'What was in the can?',
    'Kutunun içinde ne vardı?',
    ARRAY['Ham', 'A pin', 'A map'],
    ARRAY['Jambon', 'Bir iğne', 'Bir harita'],
    0,
    14
  ),
  (
    'story-g2-005',
    'Run, Kim, Run!',
    'Koş, Kim, Koş!',
    2,
    'play',
    'mimi',
    '[{"text":"Kim met a mad cat. Kim ran and ran.","textTr":"Kim kızgın bir kediyle karşılaştı. Kim koştu ve koştu.","highlightedWords":[],"location":"park"},{"text":"The cat ran at him. Dad ran to Kim.","textTr":"Kedi ona doğru koştu. Baba Kim''e doğru koştu.","highlightedWords":[],"location":"park"},{"text":"Dad set Kim on the mat. The cat hid in a den.","textTr":"Baba Kim''i paspasın üzerine koydu. Kedi inde saklandı.","highlightedWords":[],"location":"park"}]'::jsonb,
    30,
    87,
    'Why did Kim run?',
    'Kim neden koştu?',
    ARRAY['A mad cat', 'A red hen', 'A big ram'],
    ARRAY['Kızgın bir kedi', 'Kırmızı bir tavuk', 'Büyük bir koç'],
    0,
    15
  ),
  (
    'story-g2-006',
    'The Hat and the Mat',
    'Şapka ve Paspas',
    2,
    'daily life',
    'mimi',
    '[{"text":"Dad had a red hat. He set it on the mat.","textTr":"Babanın kırmızı bir şapkası vardı. Onu paspasın üzerine koydu.","highlightedWords":[],"location":"home"},{"text":"A hen sat on the hat. It is dim in the den.","textTr":"Bir tavuk şapkanın üzerine oturdu. İnde loş.","highlightedWords":[],"location":"home"},{"text":"Dad ran to the mat. He met the hen.","textTr":"Baba paspasa doğru koştu. Tavukla karşılaştı.","highlightedWords":[],"location":"home"}]'::jsonb,
    32,
    87,
    'What sat on the hat?',
    'Şapkanın üzerine ne oturdu?',
    ARRAY['A hen', 'A cat', 'A ram'],
    ARRAY['Bir tavuk', 'Bir kedi', 'Bir koç'],
    0,
    16
  ),
  (
    'story-g2-007',
    'Dim in the Den',
    'İnde Loş',
    2,
    'nature',
    'mimi',
    '[{"text":"It is dim in the den. A cat sat in it.","textTr":"İnde loş. Bir kedi içinde oturdu.","highlightedWords":[],"location":"cave"},{"text":"A red hen met him at the den.","textTr":"Kırmızı bir tavuk inde onunla karşılaştı.","highlightedWords":[],"location":"cave"},{"text":"The hen sat on a mat. The cat ran.","textTr":"Tavuk bir paspasın üzerine oturdu. Kedi koştu.","highlightedWords":[],"location":"cave"}]'::jsonb,
    28,
    88,
    'Who sat in the den?',
    'İnde kim oturdu?',
    ARRAY['A cat', 'A hen', 'Dad'],
    ARRAY['Bir kedi', 'Bir tavuk', 'Baba'],
    0,
    17
  ),
  (
    'story-g2-008',
    'The Kid and the Pet',
    'Çocuk ve Evcil Hayvan',
    2,
    'animals',
    'mimi',
    '[{"text":"A kid met a red pet. The pet sat on a mat.","textTr":"Bir çocuk kırmızı bir evcil hayvanla karşılaştı. Evcil hayvan bir paspas üzerine oturdu.","highlightedWords":[],"location":"home"},{"text":"The kid set a pen on the mat. The pet hid it.","textTr":"Çocuk paspasın üzerine bir kalem koydu. Evcil hayvan onu sakladı.","highlightedWords":[],"location":"home"},{"text":"Dad ran in. He met the pet. He had a cap.","textTr":"Baba koşarak içeri girdi. Evcil hayvanla karşılaştı. Kasketi vardı.","highlightedWords":[],"location":"home"}]'::jsonb,
    35,
    87,
    'What did the pet hide?',
    'Evcil hayvan neyi sakladı?',
    ARRAY['A pen', 'A cap', 'A mat'],
    ARRAY['Bir kalem', 'Bir kasket', 'Bir paspas'],
    0,
    18
  ),
  (
    'story-g2-009',
    'Men and Hens',
    'Erkekler ve Tavuklar',
    2,
    'farm life',
    'mimi',
    '[{"text":"The men ran to the den. The hens sat on a mat.","textTr":"Erkekler ine doğru koştu. Tavuklar bir paspasta oturdu.","highlightedWords":[],"location":"farm"},{"text":"A red hen met a mad ram. The ram ran.","textTr":"Kırmızı bir tavuk kızgın bir koçla karşılaştı. Koç koştu.","highlightedWords":[],"location":"farm"},{"text":"The men set the mat in the den. It is dim.","textTr":"Erkekler paspası ine koydu. Loş.","highlightedWords":[],"location":"farm"}]'::jsonb,
    33,
    88,
    'Where did the men run?',
    'Erkekler nereye koştu?',
    ARRAY['To the den', 'To the mat', 'To the farm'],
    ARRAY['İne doğru', 'Paspasa doğru', 'Çiftliğe doğru'],
    0,
    19
  ),
  (
    'story-g2-010',
    'Rip and Dip',
    'Yırt ve Daldır',
    2,
    'play',
    'mimi',
    '[{"text":"I rip the map. I dip it in the tin.","textTr":"Haritayı yırtıyorum. Onu tenekenin içine daldırıyorum.","highlightedWords":[],"location":"home"},{"text":"Dad is mad. He met me at the mat.","textTr":"Baba kızgın. Paspasta benimle karşılaştı.","highlightedWords":[],"location":"home"},{"text":"I set the map on the mat. I sat and had a nap.","textTr":"Haritayı paspasın üzerine koydum. Oturdum ve şekerleme yaptım.","highlightedWords":[],"location":"home"}]'::jsonb,
    32,
    88,
    'What did Dad think when I ripped the map?',
    'Baba haritayı yırttığımda ne düşündü?',
    ARRAY['He was mad', 'He ran', 'He hid'],
    ARRAY['Kızdı', 'Koştu', 'Saklandı'],
    0,
    20
  ),
  (
    'story-g3-001',
    'The Big Dog',
    'Büyük Köpek',
    3,
    'animals',
    'mimi',
    '[{"text":"A big dog sat on a log. It got a bug.","textTr":"Büyük bir köpek bir kütük üzerine oturdu. Bir böcek buldu.","highlightedWords":[],"location":"forest"},{"text":"The dog ran in the fog. It got mud on its leg.","textTr":"Köpek siste koştu. Bacağına çamur bulaştı.","highlightedWords":[],"location":"forest"},{"text":"The big dog got on the bus. It had fun!","textTr":"Büyük köpek otobüse bindi. Çok eğlendi!","highlightedWords":[],"location":"town"}]'::jsonb,
    33,
    87,
    'Where did the dog run?',
    'Köpek nerede koştu?',
    ARRAY['In the fog', 'On a log', 'On the bus'],
    ARRAY['Siste', 'Bir kütük üzerinde', 'Otobüste'],
    0,
    21
  ),
  (
    'story-g3-002',
    'Fun in the Sun',
    'Güneşte Eğlence',
    3,
    'outdoor',
    'mimi',
    '[{"text":"We got a big bun. We sat in the sun.","textTr":"Büyük bir çörek aldık. Güneşte oturduk.","highlightedWords":[],"location":"park"},{"text":"A bug sat on the bun. It got a lot of fun.","textTr":"Bir böcek çöreğin üzerine oturdu. Çok eğlendi.","highlightedWords":[],"location":"park"},{"text":"We ran and got the bus. It is fun!","textTr":"Koşup otobüse yetiştik. Çok eğlenceli!","highlightedWords":[],"location":"park"}]'::jsonb,
    31,
    87,
    'What sat on the bun?',
    'Çöreğin üzerine ne oturdu?',
    ARRAY['A bug', 'A dog', 'A cat'],
    ARRAY['Bir böcek', 'Bir köpek', 'Bir kedi'],
    0,
    22
  ),
  (
    'story-g3-003',
    'A Bug on a Log',
    'Kütükteki Böcek',
    3,
    'nature',
    'mimi',
    '[{"text":"A big bug sat on a log in the fog.","textTr":"Büyük bir böcek, siste bir kütüğün üzerine oturdu.","highlightedWords":[],"location":"forest"},{"text":"A dog ran up to the log. It got the bug.","textTr":"Bir köpek kütüğe doğru koştu. Böceği buldu.","highlightedWords":[],"location":"forest"},{"text":"The bug got on the dog. The dog had fun!","textTr":"Böcek köpeğin üzerine çıktı. Köpek çok eğlendi!","highlightedWords":[],"location":"forest"}]'::jsonb,
    31,
    87,
    'What was on the log?',
    'Kütüğün üzerinde ne vardı?',
    ARRAY['A bug', 'A dog', 'A bun'],
    ARRAY['Bir böcek', 'Bir köpek', 'Bir çörek'],
    0,
    23
  ),
  (
    'story-g3-004',
    'Bob and the Bus',
    'Bob ve Otobüs',
    3,
    'adventure',
    'mimi',
    '[{"text":"Bob ran to get the bus. He got a big leg up.","textTr":"Bob otobüse yetişmek için koştu. Büyük bir adım attı.","highlightedWords":[],"location":"town"},{"text":"A big dog got on the bus. Bob sat on a log.","textTr":"Büyük bir köpek otobüse bindi. Bob bir kütüğe oturdu.","highlightedWords":[],"location":"town"},{"text":"Bob got a lot of fun on the bus. He had a bun.","textTr":"Bob otobüste çok eğlendi. Bir çöreği vardı.","highlightedWords":[],"location":"town"}]'::jsonb,
    37,
    87,
    'What did Bob have on the bus?',
    'Bob otobüste ne yedi?',
    ARRAY['A bun', 'A log', 'A bug'],
    ARRAY['Bir çörek', 'Bir kütük', 'Bir böcek'],
    0,
    24
  ),
  (
    'story-g3-005',
    'Fog on the Hill',
    'Tepedeki Sis',
    3,
    'nature',
    'mimi',
    '[{"text":"There is a lot of fog on the hill. A big dog sat.","textTr":"Tepede çok sis var. Büyük bir köpek oturdu.","highlightedWords":[],"location":"hill"},{"text":"The dog got up. It ran in the fog and got mud.","textTr":"Köpek ayağa kalktı. Siste koştu ve çamura bulaştı.","highlightedWords":[],"location":"hill"},{"text":"A bug sat on a log. It had fun in the fog.","textTr":"Bir böcek kütüğe oturdu. Siste eğlendi.","highlightedWords":[],"location":"hill"}]'::jsonb,
    37,
    87,
    'What did the dog get in the fog?',
    'Köpek siste neye bulaştı?',
    ARRAY['Mud', 'A bug', 'A bun'],
    ARRAY['Çamur', 'Bir böcek', 'Bir çörek'],
    0,
    25
  ),
  (
    'story-g3-006',
    'The Big Red Bus',
    'Büyük Kırmızı Otobüs',
    3,
    'adventure',
    'mimi',
    '[{"text":"A big red bus got to the lot. I ran to get on.","textTr":"Büyük kırmızı bir otobüs parka geldi. Binmek için koştum.","highlightedWords":[],"location":"town"},{"text":"A dog got on the bus. It sat on the mat.","textTr":"Bir köpek otobüse bindi. Paspas üzerine oturdu.","highlightedWords":[],"location":"town"},{"text":"We had fun on the big red bus. What a lot of fun!","textTr":"Büyük kırmızı otobüste çok eğlendik. Ne çok eğlence!","highlightedWords":[],"location":"town"}]'::jsonb,
    37,
    87,
    'What color is the bus?',
    'Otobüs ne renktir?',
    ARRAY['Red', 'Tan', 'Dim'],
    ARRAY['Kırmızı', 'Ten rengi', 'Loş'],
    0,
    26
  ),
  (
    'story-g3-007',
    'Get the Bug',
    'Böceği Yakala',
    3,
    'play',
    'mimi',
    '[{"text":"A big bug sat on a log. Get the bug!","textTr":"Büyük bir böcek kütüğün üzerine oturdu. Böceği yakala!","highlightedWords":[],"location":"garden"},{"text":"I got the bug. I set it on the mat.","textTr":"Böceği yakaladım. Paspasın üzerine koydum.","highlightedWords":[],"location":"garden"},{"text":"The bug ran. It got on my leg. Fun!","textTr":"Böcek koştu. Bacağıma çıktı. Eğlenceli!","highlightedWords":[],"location":"garden"}]'::jsonb,
    29,
    88,
    'Where did the bug go at the end?',
    'Böcek sonunda nereye gitti?',
    ARRAY['On my leg', 'On the mat', 'On the log'],
    ARRAY['Bacağıma', 'Paspasa', 'Kütüğe'],
    0,
    27
  ),
  (
    'story-g3-008',
    'Lug the Log',
    'Kütüğü Taşı',
    3,
    'adventure',
    'mimi',
    '[{"text":"Dad got a big log. He had to lug it.","textTr":"Baba büyük bir kütük aldı. Onu taşımak zorundaydı.","highlightedWords":[],"location":"forest"},{"text":"A bug sat on the log. The dog ran to get it.","textTr":"Bir böcek kütüğün üzerine oturdu. Köpek onu almak için koştu.","highlightedWords":[],"location":"forest"},{"text":"Dad set the log on the mat. He had fun.","textTr":"Baba kütüğü paspasın üzerine koydu. Eğlendi.","highlightedWords":[],"location":"home"}]'::jsonb,
    32,
    88,
    'What did Dad get from the forest?',
    'Baba ormandan ne aldı?',
    ARRAY['A big log', 'A big bug', 'A big dog'],
    ARRAY['Büyük bir kütük', 'Büyük bir böcek', 'Büyük bir köpek'],
    0,
    28
  ),
  (
    'story-g3-009',
    'Bun for Fun',
    'Eğlence İçin Çörek',
    3,
    'food',
    'mimi',
    '[{"text":"I got a big bun. It is a lot of fun!","textTr":"Büyük bir çörek aldım. Çok eğlenceli!","highlightedWords":[],"location":"kitchen"},{"text":"A dog ran to get the bun. I set it on a log.","textTr":"Bir köpek çöreği almak için koştu. Onu bir kütüğün üzerine koydum.","highlightedWords":[],"location":"garden"},{"text":"The dog sat and had fun. We got a lot of buns!","textTr":"Köpek oturdu ve eğlendi. Çok çöreğimiz oldu!","highlightedWords":[],"location":"garden"}]'::jsonb,
    36,
    87,
    'What did the dog want?',
    'Köpek ne istedi?',
    ARRAY['The bun', 'The log', 'A bug'],
    ARRAY['Çöreği', 'Kütüğü', 'Bir böceği'],
    0,
    29
  ),
  (
    'story-g3-010',
    'The Dog and the Hen',
    'Köpek ve Tavuk',
    3,
    'animals',
    'mimi',
    '[{"text":"A big dog met a red hen. They sat on a log.","textTr":"Büyük bir köpek kırmızı bir tavukla karşılaştı. Bir kütük üzerine oturdular.","highlightedWords":[],"location":"farm"},{"text":"The hen got a bug. The dog got a bun.","textTr":"Tavuk bir böcek aldı. Köpek bir çörek aldı.","highlightedWords":[],"location":"farm"},{"text":"They had a lot of fun in the fog.","textTr":"Siste çok eğlendiler.","highlightedWords":[],"location":"farm"}]'::jsonb,
    31,
    87,
    'What did the hen get?',
    'Tavuk ne aldı?',
    ARRAY['A bug', 'A bun', 'A log'],
    ARRAY['Bir böcek', 'Bir çörek', 'Bir kütük'],
    0,
    30
  ),
  (
    'story-g4-001',
    'A Rainy Day',
    'Yağmurlu Bir Gün',
    4,
    'weather',
    'mimi',
    '[{"text":"The rain came. We got our coats on.","textTr":"Yağmur geldi. Montlarımızı giydik.","highlightedWords":[],"location":"home"},{"text":"Dad tied the boat to the road. He did not want to sail.","textTr":"Baba tekneyi yola bağladı. Yelken açmak istemedi.","highlightedWords":[],"location":"dock"},{"text":"A toad sat on a log. It waited for the rain to stop.","textTr":"Bir kurbağa kütüğe oturdu. Yağmurun durmasını bekledi.","highlightedWords":[],"location":"garden"}]'::jsonb,
    34,
    87,
    'Why did Dad tie the boat?',
    'Baba neden tekneyi bağladı?',
    ARRAY['He did not want to sail', 'He felt tired', 'He saw a toad'],
    ARRAY['Yelken açmak istemedi', 'Acı hissetti', 'Kurbağa gördü'],
    0,
    31
  ),
  (
    'story-g4-002',
    'The Boat Trip',
    'Tekne Gezisi',
    4,
    'adventure',
    'mimi',
    '[{"text":"We got on the boat. The sail was tied.","textTr":"Tekneye bindik. Yelken bağlandı.","highlightedWords":[],"location":"ocean"},{"text":"A goat sat on the road. It moaned and moaned.","textTr":"Bir keçi yolda oturdu. İnledi ve inledi.","highlightedWords":[],"location":"road"},{"text":"We sailed for a long time. Our feet got wet.","textTr":"Uzun süre yelken açtık. Ayaklarımız ıslandı.","highlightedWords":[],"location":"ocean"}]'::jsonb,
    29,
    87,
    'What got wet on the boat?',
    'Teknede ne ıslandı?',
    ARRAY['Our feet', 'The goat', 'The sail'],
    ARRAY['Ayaklarımız', 'Keçi', 'Yelken'],
    0,
    32
  ),
  (
    'story-g4-003',
    'Feet in the Sand',
    'Kumda Ayaklar',
    4,
    'beach',
    'mimi',
    '[{"text":"I feel the sand on my feet. It feels deep.","textTr":"Ayaklarımda kumu hissediyorum. Çok derin hissettiriyor.","highlightedWords":[],"location":"beach"},{"text":"A bee sat on the tree near the road. It buzzed.","textTr":"Bir arı yolun yakınındaki ağaca kondu. Vızıldadı.","highlightedWords":[],"location":"beach"},{"text":"We met the goat at the fort. Its tail wagged.","textTr":"Kaleye yakın keçiyle karşılaştık. Kuyruğu sallandı.","highlightedWords":[],"location":"beach"}]'::jsonb,
    31,
    86,
    'Where did the bee sit?',
    'Arı nereye kondu?',
    ARRAY['On the tree', 'On the goat', 'On the road'],
    ARRAY['Ağaca', 'Keçiye', 'Yola'],
    0,
    33
  ),
  (
    'story-g4-004',
    'The Road Home',
    'Eve Giden Yol',
    4,
    'daily life',
    'mimi',
    '[{"text":"I sailed on the road. The rain fell for a long time.","textTr":"Yolda yelken açtım. Yağmur uzun süre yağdı.","highlightedWords":[],"location":"road"},{"text":"A toad sat on the road. I tied my coat.","textTr":"Bir kurbağa yolda oturdu. Montumu bağladım.","highlightedWords":[],"location":"road"},{"text":"I got home. I could see the tree and feel the heat.","textTr":"Eve ulaştım. Ağacı görebiliyordum ve sıcaklığı hissedebiliyordum.","highlightedWords":[],"location":"home"}]'::jsonb,
    34,
    86,
    'What sat on the road?',
    'Yolda ne oturdu?',
    ARRAY['A toad', 'A goat', 'A bee'],
    ARRAY['Bir kurbağa', 'Bir keçi', 'Bir arı'],
    0,
    34
  ),
  (
    'story-g4-005',
    'Born to Fly',
    'Uçmak İçin Doğdu',
    4,
    'nature',
    'mimi',
    '[{"text":"A bee was born near a tree. It had a tied tie.","textTr":"Bir ağacın yakınında bir arı doğdu. Bağlı bir kravat taşıyordu.","highlightedWords":[],"location":"garden"},{"text":"It flew for the corn in the rain. Its feet felt the cold.","textTr":"Yağmurda mısır için uçtu. Ayakları soğuğu hissetti.","highlightedWords":[],"location":"farm"},{"text":"The bee met a goat on the road. They both felt free!","textTr":"Arı yolda bir keçiyle karşılaştı. İkisi de özgür hissetti!","highlightedWords":[],"location":"road"}]'::jsonb,
    37,
    86,
    'Where was the bee born?',
    'Arı nerede doğdu?',
    ARRAY['Near a tree', 'On a boat', 'On the road'],
    ARRAY['Bir ağacın yakınında', 'Bir teknede', 'Yolda'],
    0,
    35
  ),
  (
    'story-g4-006',
    'The Corn and the Goat',
    'Mısır ve Keçi',
    4,
    'farm life',
    'mimi',
    '[{"text":"A goat on a boat got to the corn. It tried to eat it.","textTr":"Bir teknedeki keçi mısıra ulaştı. Onu yemeye çalıştı.","highlightedWords":[],"location":"farm"},{"text":"The goat cried. The corn was for the bee born on the road.","textTr":"Keçi ağladı. Mısır yolda doğan arı içindi.","highlightedWords":[],"location":"farm"},{"text":"The bee fed the goat. Both felt joy.","textTr":"Arı keçiyi besledi. İkisi de sevinç duydu.","highlightedWords":[],"location":"farm"}]'::jsonb,
    35,
    86,
    'Who fed the goat?',
    'Keçiyi kim besledi?',
    ARRAY['The bee', 'The toad', 'Dad'],
    ARRAY['Arı', 'Kurbağa', 'Baba'],
    0,
    36
  ),
  (
    'story-g4-007',
    'Wait for the Boat',
    'Tekneyi Bekle',
    4,
    'adventure',
    'mimi',
    '[{"text":"We wait for the boat in the rain. A sail is tied.","textTr":"Yağmurda tekneyi bekliyoruz. Bir yelken bağlı.","highlightedWords":[],"location":"dock"},{"text":"A toad sat on the road. A bee flew to the tree.","textTr":"Bir kurbağa yolda oturdu. Bir arı ağaca uçtu.","highlightedWords":[],"location":"dock"},{"text":"The boat came! We ran to meet it. It felt great.","textTr":"Tekne geldi! Karşılamak için koştuk. Harika hissettirdi.","highlightedWords":[],"location":"ocean"}]'::jsonb,
    35,
    86,
    'What did the bee do?',
    'Arı ne yaptı?',
    ARRAY['Flew to the tree', 'Sat on the road', 'Tied the boat'],
    ARRAY['Ağaca uçtu', 'Yolda oturdu', 'Tekneyi bağladı'],
    0,
    37
  ),
  (
    'story-g4-008',
    'The Tail of the Toad',
    'Kurbağanın Kuyruğu',
    4,
    'nature',
    'mimi',
    '[{"text":"A toad sat near the deep sea. Its tail was short.","textTr":"Bir kurbağa derin denizin yanında oturdu. Kuyruğu kısaydı.","highlightedWords":[],"location":"beach"},{"text":"A goat ran on the road. The toad tried to see it.","textTr":"Bir keçi yolda koştu. Kurbağa onu görmeye çalıştı.","highlightedWords":[],"location":"beach"},{"text":"The toad felt free. It sailed on the sea on a boat.","textTr":"Kurbağa özgür hissetti. Denizde teknede yelken açtı.","highlightedWords":[],"location":"ocean"}]'::jsonb,
    35,
    86,
    'Where was the toad at first?',
    'Kurbağa ilk başta neredeydi?',
    ARRAY['Near the deep sea', 'On the road', 'On the boat'],
    ARRAY['Derin denizin yanında', 'Yolda', 'Teknede'],
    0,
    38
  ),
  (
    'story-g4-009',
    'The Bee and the Tree',
    'Arı ve Ağaç',
    4,
    'nature',
    'mimi',
    '[{"text":"A bee was born in a tree. It saw the road and the sea.","textTr":"Bir arı ağaçta doğdu. Yolu ve denizi gördü.","highlightedWords":[],"location":"forest"},{"text":"The bee tried to get corn for the goat. It flew in the rain.","textTr":"Arı keçi için mısır almaya çalıştı. Yağmurda uçtu.","highlightedWords":[],"location":"farm"},{"text":"The goat felt the bee on its tail. It moaned with joy.","textTr":"Keçi kuyruğundaki arıyı hissetti. Sevinçle inledi.","highlightedWords":[],"location":"farm"}]'::jsonb,
    40,
    86,
    'What did the bee try to get?',
    'Arı ne almaya çalıştı?',
    ARRAY['Corn', 'A boat', 'A seed'],
    ARRAY['Mısır', 'Bir tekne', 'Bir tohum'],
    0,
    39
  ),
  (
    'story-g4-010',
    'Sail in the Rain',
    'Yağmurda Yelken',
    4,
    'adventure',
    'mimi',
    '[{"text":"The rain came. We sailed on the sea in our coats.","textTr":"Yağmur geldi. Montlarımızla denizde yelken açtık.","highlightedWords":[],"location":"ocean"},{"text":"A goat sat in the boat. It tried to eat the mail.","textTr":"Bir keçi teknede oturdu. Mektubu yemeye çalıştı.","highlightedWords":[],"location":"ocean"},{"text":"We tied the boat to the tree. Our feet felt the rain.","textTr":"Tekneyi ağaca bağladık. Ayaklarımız yağmuru hissetti.","highlightedWords":[],"location":"dock"}]'::jsonb,
    35,
    86,
    'What did the goat try to eat?',
    'Keçi ne yemeye çalıştı?',
    ARRAY['The mail', 'The rope', 'The coat'],
    ARRAY['Mektubu', 'Halatı', 'Montu'],
    0,
    40
  ),
  (
    'story-g5-001',
    'The Zig-Zag Path',
    'Zikzak Yol',
    5,
    'adventure',
    'mimi',
    '[{"text":"We ran down the zig-zag path. The wind made a long song.","textTr":"Zikzak yoldan aşağı koştuk. Rüzgar uzun bir şarkı söyledi.","highlightedWords":[],"location":"forest"},{"text":"A van was on the road. It had a big boot.","textTr":"Yolda bir minibüs vardı. Büyük bir bagajı vardı.","highlightedWords":[],"location":"road"},{"text":"We took a book and sat on a log. What a cool path!","textTr":"Bir kitap alıp kütük üzerine oturduk. Ne harika bir yol!","highlightedWords":[],"location":"forest"}]'::jsonb,
    36,
    86,
    'What did they take on the path?',
    'Yolda ne aldılar?',
    ARRAY['A book', 'A van', 'A wig'],
    ARRAY['Bir kitap', 'Bir minibüs', 'Bir peruk'],
    0,
    41
  ),
  (
    'story-g5-002',
    'Win the Race',
    'Yarışı Kazan',
    5,
    'sports',
    'mimi',
    '[{"text":"I want to win the ring race! I zipped along.","textTr":"Halka yarışını kazanmak istiyorum! Hızla geçtim.","highlightedWords":[],"location":"park"},{"text":"A vet in a van rang a bell. We ran long and fast.","textTr":"Bir minibüsteki veteriner zil çaldı. Uzun ve hızlı koştuk.","highlightedWords":[],"location":"park"},{"text":"I won! I took a cool swim in the pool. It felt good.","textTr":"Kazandım! Havuzda serin bir yüzüş yaptım. İyi hissettirdi.","highlightedWords":[],"location":"pool"}]'::jsonb,
    36,
    85,
    'Where did the winner swim?',
    'Kazanan nerede yüzdü?',
    ARRAY['In the pool', 'In the sea', 'In a vat'],
    ARRAY['Havuzda', 'Denizde', 'Fıçıda'],
    0,
    42
  ),
  (
    'story-g5-003',
    'A Wing and a Wish',
    'Bir Kanat ve Bir Dilek',
    5,
    'nature',
    'mimi',
    '[{"text":"A king with a long wing sat by the moon pool.","textTr":"Uzun kanatlı bir kral ay havuzunun yanında oturdu.","highlightedWords":[],"location":"garden"},{"text":"He wished for a book and a cook. The wind rang a bell.","textTr":"Bir kitap ve bir aşçı diledi. Rüzgar bir zil çaldı.","highlightedWords":[],"location":"garden"},{"text":"A van brought food. The king felt a zing of joy!","textTr":"Bir minibüs yemek getirdi. Kral bir sevinç duygusu hissetti!","highlightedWords":[],"location":"home"}]'::jsonb,
    35,
    85,
    'What did the king wish for?',
    'Kral ne diledi?',
    ARRAY['A book and a cook', 'A van and food', 'A pool and a ring'],
    ARRAY['Kitap ve aşçı', 'Minibüs ve yemek', 'Havuz ve halka'],
    0,
    43
  ),
  (
    'story-g5-004',
    'Books and Looks',
    'Kitaplar ve Bakışlar',
    5,
    'school',
    'mimi',
    '[{"text":"I took a look at my book. It was good!","textTr":"Kitabıma baktım. İyiydi!","highlightedWords":[],"location":"classroom"},{"text":"A vet rang the bell. We stood in a long ring.","textTr":"Bir veteriner zil çaldı. Uzun bir halkada durduk.","highlightedWords":[],"location":"classroom"},{"text":"The cook had wool socks. She sang a song and cooked.","textTr":"Aşçının yün çorapları vardı. Şarkı söyledi ve pişirdi.","highlightedWords":[],"location":"kitchen"}]'::jsonb,
    32,
    85,
    'What did the cook have on her feet?',
    'Aşçının ayaklarında ne vardı?',
    ARRAY['Wool socks', 'Cool boots', 'A ring'],
    ARRAY['Yün çoraplar', 'Serin çizmeler', 'Bir halka'],
    0,
    44
  ),
  (
    'story-g5-005',
    'The Zoo Trip',
    'Hayvanat Bahçesi Gezisi',
    5,
    'animals',
    'mimi',
    '[{"text":"We took a van to the zoo. The moon was still in the sky.","textTr":"Hayvanat bahçesine minibüsle gittik. Ay hâlâ gökyüzündeydi.","highlightedWords":[],"location":"zoo"},{"text":"A vet sang a song near the cool pool. A wing rang in the wind.","textTr":"Bir veteriner serin havuzun yanında şarkı söyledi. Rüzgarda bir kanat çınladı.","highlightedWords":[],"location":"zoo"},{"text":"We took a long look at the moon. We had good food.","textTr":"Aya uzun uzun baktık. İyi yemek yedik.","highlightedWords":[],"location":"zoo"}]'::jsonb,
    41,
    85,
    'How did they get to the zoo?',
    'Hayvanat bahçesine nasıl gittiler?',
    ARRAY['By van', 'By boat', 'On foot'],
    ARRAY['Minibüsle', 'Tekneyle', 'Yürüyerek'],
    0,
    45
  ),
  (
    'story-g5-006',
    'The King at the Pool',
    'Havuzdaki Kral',
    5,
    'play',
    'mimi',
    '[{"text":"The king stood by the pool. He had his wool coat on.","textTr":"Kral havuzun yanında durdu. Yün montunu giymişti.","highlightedWords":[],"location":"pool"},{"text":"He took off his wig and sang a long song.","textTr":"Peruğunu çıkardı ve uzun bir şarkı söyledi.","highlightedWords":[],"location":"pool"},{"text":"He jumped in. The water felt cool and good!","textTr":"İçine atladı. Su serin ve güzel hissettirdi!","highlightedWords":[],"location":"pool"}]'::jsonb,
    31,
    85,
    'What did the king take off?',
    'Kral neyi çıkardı?',
    ARRAY['His wig', 'His ring', 'His boot'],
    ARRAY['Peruğunu', 'Yüzüğünü', 'Çizmeyi'],
    0,
    46
  ),
  (
    'story-g5-007',
    'Zoom to the Moon',
    'Aya Uç',
    5,
    'space',
    'mimi',
    '[{"text":"A van went zoom to the moon. It had a long wing.","textTr":"Bir minibüs aya doğru uçtu. Uzun bir kanadı vardı.","highlightedWords":[],"location":"space"},{"text":"A vet stood on the moon. She sang a cool song.","textTr":"Bir veteriner ayda durdu. Harika bir şarkı söyledi.","highlightedWords":[],"location":"space"},{"text":"They cooked food and took a good long look at the stars.","textTr":"Yemek pişirdiler ve yıldızlara uzun uzun baktılar.","highlightedWords":[],"location":"space"}]'::jsonb,
    35,
    85,
    'Who stood on the moon?',
    'Ayda kim durdu?',
    ARRAY['A vet', 'A king', 'A cook'],
    ARRAY['Bir veteriner', 'Bir kral', 'Bir aşçı'],
    0,
    47
  ),
  (
    'story-g5-008',
    'The Wool Van',
    'Yün Minibüsü',
    5,
    'daily life',
    'mimi',
    '[{"text":"A van with wool rang its bell. It was a long ride.","textTr":"Yünlü bir minibüs zilini çaldı. Uzun bir yolculuktu.","highlightedWords":[],"location":"road"},{"text":"The cook took the wool and made a good wig.","textTr":"Aşçı yünü aldı ve güzel bir peruk yaptı.","highlightedWords":[],"location":"home"},{"text":"The king tried the wig. He stood by the pool and sang.","textTr":"Kral peruğu denedi. Havuzun yanında durdu ve şarkı söyledi.","highlightedWords":[],"location":"pool"}]'::jsonb,
    34,
    85,
    'What did the cook make with the wool?',
    'Aşçı yünle ne yaptı?',
    ARRAY['A wig', 'A boot', 'A ring'],
    ARRAY['Bir peruk', 'Bir çizme', 'Bir halka'],
    0,
    48
  ),
  (
    'story-g5-009',
    'Cook Good Food',
    'İyi Yemek Pişir',
    5,
    'food',
    'mimi',
    '[{"text":"The cook stood in the room. She took a book to look at.","textTr":"Aşçı odada durdu. Bakmak için bir kitap aldı.","highlightedWords":[],"location":"kitchen"},{"text":"She sang a song. The food smelled good.","textTr":"Şarkı söyledi. Yemek güzel kokuyordu.","highlightedWords":[],"location":"kitchen"},{"text":"A king came in and took a look. He rang a bell for the vet.","textTr":"Bir kral içeri girdi ve baktı. Veteriner için zil çaldı.","highlightedWords":[],"location":"kitchen"}]'::jsonb,
    36,
    85,
    'What did the cook use to help her cook?',
    'Aşçı pişirirken ne kullandı?',
    ARRAY['A book', 'A van', 'A ring'],
    ARRAY['Bir kitap', 'Bir minibüs', 'Bir halka'],
    0,
    49
  ),
  (
    'story-g5-010',
    'Zing in the Wind',
    'Rüzgarda Ses',
    5,
    'nature',
    'mimi',
    '[{"text":"The wind rang with a long zing. A van stood still.","textTr":"Rüzgar uzun bir ses çıkararak çınladı. Bir minibüs hareketsiz durdu.","highlightedWords":[],"location":"park"},{"text":"A cook sang a cool song. The king took a book.","textTr":"Bir aşçı harika bir şarkı söyledi. Kral bir kitap aldı.","highlightedWords":[],"location":"park"},{"text":"We stood by the pool. The moon looked cool.","textTr":"Havuzun yanında durduk. Ay harika görünüyordu.","highlightedWords":[],"location":"pool"}]'::jsonb,
    31,
    85,
    'What did the king take?',
    'Kral ne aldı?',
    ARRAY['A book', 'A wig', 'A van'],
    ARRAY['Bir kitap', 'Bir peruk', 'Bir minibüs'],
    0,
    50
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  title_tr = EXCLUDED.title_tr,
  phonics_group = EXCLUDED.phonics_group,
  topic = EXCLUDED.topic,
  mascot_id = EXCLUDED.mascot_id,
  scenes = EXCLUDED.scenes,
  word_count = EXCLUDED.word_count,
  decodability_score = EXCLUDED.decodability_score,
  comprehension_question = EXCLUDED.comprehension_question,
  comprehension_question_tr = EXCLUDED.comprehension_question_tr,
  comprehension_answers = EXCLUDED.comprehension_answers,
  comprehension_answers_tr = EXCLUDED.comprehension_answers_tr,
  correct_answer_index = EXCLUDED.correct_answer_index,
  sort_order = EXCLUDED.sort_order;
