export type Activity = {
  id: string
  titleTr: string
  titleEn: string
  shortDesc: string
  topicIds: string[]
  gradeLevels: number[]
  durationMin: number
  type: 'TPR' | 'Game' | 'Song' | 'Craft' | 'RolePlay' | 'Worksheet' | 'Drawing' | 'Listening'
  materials: string[]
  steps: string[]
  variations?: string
  teacherNote?: string
  seoKeywords: string[]
}

export const activities: Activity[] = [
  {
    id: 'simon-says-actions',
    titleTr: 'Simon Diyor ki — Hareket Komutları',
    titleEn: 'Simon Says — Action Commands',
    shortDesc: 'Klasik "Simon Says" oyunu ile hareket fiilleri pratiği. Çocuk dinleyerek + bedenle pekiştirir.',
    topicIds: ['action-verbs', 'classroom', 'body-parts'],
    gradeLevels: [1, 2, 3],
    durationMin: 15,
    type: 'TPR',
    materials: ['Yok — sadece açık alan'],
    steps: [
      'Sınıfı yarım daire yap.',
      'Öğretmen: "Simon says: stand up!" — çocuk ayağa kalkar.',
      'Öğretmen "Simon says" demeden sadece "Sit down!" derse çocuk YAPMAMALI.',
      'Yapan çocuk oyundan çıkar.',
      'Son kalan kazanır.',
    ],
    variations: 'Hareket yerine vücut bölümü: "Simon says: touch your nose!" Karışık zorlaştırır.',
    teacherNote: 'İlk hafta sade tut: sadece stand up, sit down, jump, clap. Sonraki haftalarda yeni komutlar ekle.',
    seoKeywords: ['simon says türkçe', 'ingilizce hareket oyunu', 'TPR sınıf oyunu', 'action verbs etkinlik'],
  },
  {
    id: 'color-hunt',
    titleTr: 'Renk Avı',
    titleEn: 'Color Hunt',
    shortDesc: 'Sınıfta veya evde renk arama oyunu. Çocuk her renkten bir nesne bulup İngilizce söyler.',
    topicIds: ['colors', 'classroom', 'school-items'],
    gradeLevels: [1, 2],
    durationMin: 10,
    type: 'Game',
    materials: ['Sınıf veya ev (gerçek nesneler)'],
    steps: [
      'Öğretmen bir renk söyler: "Red!"',
      'Çocuklar 30 saniye içinde sınıfta kırmızı bir nesne bulur.',
      'Sırayla gösterip "A red book!" / "A red pencil!" derler.',
      'Yeni renk: "Blue!"',
      'Tekrar arama.',
    ],
    variations: 'İki takıma böl. Hangi takım önce 5 farklı kırmızı nesne bulur?',
    teacherNote: 'Renk + nesne ikilisi pekişir. Renk öğretiminin en pratik etkinliklerinden biri.',
    seoKeywords: ['renkler oyunu ingilizce', 'color hunt', 'sınıf renk etkinliği', 'colors ilkokul oyun'],
  },
  {
    id: 'animal-charades',
    titleTr: 'Hayvan Pantomim',
    titleEn: 'Animal Charades',
    shortDesc: 'Çocuk bir hayvanı sessizce canlandırır, sınıf İngilizce tahmin eder.',
    topicIds: ['animals', 'action-verbs'],
    gradeLevels: [1, 2, 3, 4],
    durationMin: 15,
    type: 'Game',
    materials: ['Kart (hayvan adı yazılı)'],
    steps: [
      'Hayvan kartlarını kapaklı yığ.',
      'Bir çocuk kart çeker, gizler.',
      'O hayvanı sessizce canlandırır (ses çıkarmadan).',
      'Sınıf "Is it a lion? Is it a cat?" diye tahmin eder.',
      'Doğru bilen sıradaki olur.',
    ],
    variations: 'Sesli versiyon: çocuk hayvan sesini çıkarır ("Meow!"). Daha kolay.',
    teacherNote: 'Beden + dil + hayal gücü — kapsamlı bir TPR etkinliği. 4. sınıf için yetenek/can ile birleştir.',
    seoKeywords: ['hayvan oyunu ingilizce', 'animal charades', 'pantomim ingilizce', 'hayvanlar etkinlik'],
  },
  {
    id: 'family-photo-introduction',
    titleTr: 'Aile Fotoğrafı Tanıtımı',
    titleEn: 'Family Photo Introduction',
    shortDesc: 'Her çocuk evden aile fotoğrafı getirir, "This is my mother..." kalıbıyla tanıtır.',
    topicIds: ['family', 'this-that', 'possessives'],
    gradeLevels: [2, 3],
    durationMin: 20,
    type: 'RolePlay',
    materials: ['Çocuğun aile fotoğrafı (önceden istenir)'],
    steps: [
      'Bir hafta önce çocuklardan aile fotoğrafı istenir.',
      'Her çocuk sınıfın önüne gelir.',
      'Fotoğrafı gösterir: "This is my family."',
      'Her üyeyi tanıtır: "This is my mother. Her name is Ayşe."',
      'Sonunda sınıf 1-2 soru sorar: "Is your sister tall?"',
    ],
    variations: 'Fotoğraf yok ise çizim: çocuk ailesini çizer, çizimden tanıtır.',
    teacherNote: 'Çocuk kendi ailesini anlattığı için motivasyon en yüksek. "This is my..." kalıbı doğal oturur.',
    seoKeywords: ['aile fotoğrafı etkinlik', 'this is my mother', 'family ingilizce', 'aile tanıtım'],
  },
  {
    id: 'counting-fingers',
    titleTr: 'Parmak Sayma',
    titleEn: 'Counting with Fingers',
    shortDesc: 'Çocuk parmaklarıyla sayar, "One, two, three..." sözlü pratiği yapar.',
    topicIds: ['numbers-1-10', 'body-parts'],
    gradeLevels: [1],
    durationMin: 10,
    type: 'TPR',
    materials: ['Yok'],
    steps: [
      'Sınıfa yarım daire ol.',
      'Öğretmen: "Let\'s count!"',
      'Birlikte: "One!" (1 parmak), "Two!" (2 parmak)...',
      '10\'a kadar say.',
      'Geri sayma: "Ten, nine, eight..."',
    ],
    variations: 'Şarkı versiyonu: "Ten little fingers" şarkısıyla say. Müzik + sayı.',
    teacherNote: 'Sayma 1. sınıfın ilk haftalarında her gün rutin yap. 2 hafta sonunda otomatikleşir.',
    seoKeywords: ['parmak sayma ingilizce', 'one two three öğretim', 'sayma 1 sınıf', 'numbers 1-10 etkinlik'],
  },
  {
    id: 'weather-pano-daily',
    titleTr: 'Günlük Hava Durumu Panosu',
    titleEn: 'Daily Weather Board',
    shortDesc: 'Her sabah bir çocuk hava durumunu sınıf panosuna yapıştırır + İngilizce duyurur.',
    topicIds: ['weather', 'seasons'],
    gradeLevels: [2, 3, 4],
    durationMin: 5,
    type: 'Game',
    materials: ['Hava durumu kartları (sunny, rainy, cloudy, snowy)', 'Pano + raptiye'],
    steps: [
      'Sınıfa "Today\'s Weather" panosu as.',
      'Sabah bir çocuk gönüllü olur.',
      'Pencereden bakar, doğru kartı seçer.',
      'Sınıfa duyurur: "Today is sunny and cold."',
      'Pano altına asar.',
    ],
    variations: 'Mevsim ekle: "It is sunny because it is summer."',
    teacherNote: '5 dakika günlük rutin = 1 ayda 100 tekrar. Bu sayede hava durumu kelimeleri ezbere yerleşir.',
    seoKeywords: ['hava durumu panosu', 'weather pano', 'today is sunny', 'günlük rutin ingilizce'],
  },
  {
    id: 'food-pyramid-drawing',
    titleTr: 'Yiyecek Piramidi Çizimi',
    titleEn: 'Food Pyramid Drawing',
    shortDesc: 'Çocuk sağlıklı beslenme piramidi çizer, her bölüme İngilizce yiyecek adı yazar.',
    topicIds: ['food', 'fruits', 'vegetables', 'adjectives'],
    gradeLevels: [3, 4],
    durationMin: 25,
    type: 'Drawing',
    materials: ['A4 kâğıt', 'Renkli kalem'],
    steps: [
      'Tahtaya örnek piramit çiz: 5 katlı.',
      'Alt kat: tahıllar (bread, rice, pasta).',
      'Üst: protein (meat, fish, egg).',
      'En üst: tatlı (cake, candy).',
      'Çocuk kendi piramidini çizer, kelime yazar, renklendirir.',
    ],
    variations: 'Sağlıklı vs sağlıksız liste: 2 sütun, çocuk her yiyeceği uygun sütuna yazar.',
    teacherNote: 'Beslenme + İngilizce + sanat üçlüsü. Yetişkin yaşam dersi için de temel.',
    seoKeywords: ['yiyecek piramidi', 'food pyramid ingilizce', 'sağlıklı beslenme ingilizce', 'food etkinlik'],
  },
  {
    id: 'body-parts-song',
    titleTr: 'Head Shoulders Knees and Toes Şarkısı',
    titleEn: 'Head Shoulders Knees and Toes Song',
    shortDesc: 'Klasik vücut bölümleri şarkısı. Her kelimede çocuk o bölgeye dokunur.',
    topicIds: ['body-parts', 'action-verbs'],
    gradeLevels: [1, 2],
    durationMin: 10,
    type: 'Song',
    materials: ['Şarkı (YouTube veya kaset)'],
    steps: [
      'Şarkıyı çal: "Head, shoulders, knees and toes..."',
      'Çocuklar her kelimede o bölgeye dokunur.',
      'Şarkıyı 3 kez tekrarla, her tekrarda biraz hızlı çal.',
      'Müzik kapalıyken çocuk söyler ve hareket eder.',
    ],
    variations: 'Yarım grup söyler, diğeri hareket eder. Sonra değişirler.',
    teacherNote: 'Tüm dünyada vücut bölümleri öğretiminin altın standardı. 2 hafta sonra ezbere oturur.',
    seoKeywords: ['head shoulders knees toes', 'vücut şarkısı ingilizce', 'body parts şarkı', 'TPR şarkı'],
  },
  {
    id: 'clothes-fashion-show',
    titleTr: 'Kıyafet Defilesi',
    titleEn: 'Clothes Fashion Show',
    shortDesc: 'Çocuk en sevdiği kıyafetini İngilizce anlatır, podyumdan geçer.',
    topicIds: ['clothes', 'colors', 'this-that'],
    gradeLevels: [3, 4],
    durationMin: 20,
    type: 'RolePlay',
    materials: ['Yok (üzerindeki kıyafet)'],
    steps: [
      'Sınıfı podyum gibi düzenle.',
      'Bir çocuk öne çıkar.',
      'Kıyafetlerini söyler: "I am wearing a red t-shirt, blue jeans and white shoes."',
      'Sınıf alkışlar.',
      'Sıradaki çocuk gelir.',
    ],
    variations: 'Hayal: "Today I am a clown! I have a red nose and a big hat!"',
    teacherNote: 'Çocuk kendinden bahsettiği için motivasyon yüksek. "I am wearing..." kalıbı doğal oturur.',
    seoKeywords: ['kıyafet defilesi', 'fashion show ingilizce', 'i am wearing', 'clothes etkinlik'],
  },
  {
    id: 'school-bag-empty',
    titleTr: 'Çantamda Ne Var?',
    titleEn: "What's in My Bag?",
    shortDesc: 'Çocuk çantasındaki eşyaları tek tek çıkarır, İngilizce söyler.',
    topicIds: ['school-items', 'this-that', 'colors'],
    gradeLevels: [1, 2, 3],
    durationMin: 15,
    type: 'Game',
    materials: ['Çocuğun okul çantası'],
    steps: [
      'Bir çocuk çantasıyla sınıfın önüne gelir.',
      'Sırayla bir eşya çıkarır.',
      '"This is my pencil. It is yellow."',
      'Sınıf doğru ismi söyler.',
      'Yanlış kelime varsa düzelt.',
    ],
    variations: '"Kayıp eşya": Öğretmen bir eşya alır, çocuk bilmece çözer: "I lost my..."',
    teacherNote: 'Sınıf eşyaları + renk + iyelik üçü birden pratik. Çok kapsamlı.',
    seoKeywords: ['çantamda ne var', 'school items oyun', 'this is my pencil', 'okul eşyaları etkinlik'],
  },
  {
    id: 'days-week-board',
    titleTr: 'Haftanın Günleri Panosu',
    titleEn: 'Days of the Week Board',
    shortDesc: 'Sınıf panosu: 7 gün, her gün için aktivite/ders. Çocuk dolduruyor.',
    topicIds: ['days-of-week', 'school-subjects', 'daily-routines'],
    gradeLevels: [3, 4],
    durationMin: 15,
    type: 'Craft',
    materials: ['A3 kâğıt', 'kalem, etiket'],
    steps: [
      '7 sütun çiz: Monday-Sunday.',
      'Çocuk her gün için 1-2 ders/etkinlik yazar.',
      '"Monday: math, English." "Saturday: football, family lunch."',
      'Sınıfa asılır.',
      'Her sabah "Today is..." rutiniyle güncellenir.',
    ],
    variations: 'Bireysel günlük yerine sınıf programı: hangi ders hangi gün.',
    teacherNote: 'Hafta günleri + ders/eylem birleşir. Rutin günlük rutinle pekişir.',
    seoKeywords: ['haftanın günleri pano', 'days of week sınıf', 'on monday', 'günler ingilizce etkinlik'],
  },
  {
    id: 'feelings-emoji-board',
    titleTr: 'Duygu Emoji Panosu',
    titleEn: 'Feelings Emoji Board',
    shortDesc: 'Sınıf girişinde her çocuk gün başında ruh halini emoji ile gösterir.',
    topicIds: ['feelings', 'classroom'],
    gradeLevels: [2, 3],
    durationMin: 5,
    type: 'Craft',
    materials: ['Emoji kartları (happy, sad, angry, tired, excited)', 'İsim etiketleri'],
    steps: [
      'Sınıf duvarına 5 emoji kartı as.',
      'Sabah her çocuk kendi ismini doğru emoji altına koyar.',
      'Öğretmen: "Why are you sad, Ali?"',
      'Çocuk: "My cat is sick."',
      'Sınıf empati gösterir.',
    ],
    variations: 'Hafta sonu sonrası: Pazartesi çocuklara nasıl hissettiklerini sor.',
    teacherNote: 'Duygu okuryazarlığı + İngilizce + öz farkındalık. Çocuğu duygularını ifade etmeye alıştırır.',
    seoKeywords: ['duygu panosu', 'emoji feelings', 'how do you feel', 'feelings ilkokul etkinlik'],
  },
  {
    id: 'hobby-show-and-tell',
    titleTr: 'Hobi Tanıtımı (Show and Tell)',
    titleEn: 'Hobby Show and Tell',
    shortDesc: 'Her çocuk evden hobisi ile ilgili bir eşya getirir, 2-3 cümle ile tanıtır.',
    topicIds: ['hobbies', 'this-that', 'can-cant'],
    gradeLevels: [3, 4],
    durationMin: 25,
    type: 'RolePlay',
    materials: ['Çocuğun hobi eşyası (kitap, top, boya, vb.)'],
    steps: [
      'Bir hafta önce duyur: "Bring something about your hobby."',
      'Her çocuk sırayla gelir.',
      '"This is my book. I like reading. I read every night."',
      'Sınıf 1 soru sorar.',
      'Sıradaki gelir.',
    ],
    variations: 'Resimle: Çocuk hobisini çizer + 5 cümle yazar.',
    teacherNote: 'Tutarlı bir aylık etkinlik. Çocuk kendini ifade etmeyi pekiştirir + dinleme + soru sorma.',
    seoKeywords: ['show and tell', 'hobi tanıtımı', 'my hobby is', 'hobbies ingilizce etkinlik'],
  },
  {
    id: 'time-clock-craft',
    titleTr: 'Karton Saat Yapma',
    titleEn: 'Cardboard Clock Craft',
    shortDesc: 'Çocuk karton saat yapıp akrep yelkovanı çevirerek saatleri öğrenir.',
    topicIds: ['time-telling', 'numbers-1-10', 'numbers-11-100'],
    gradeLevels: [4],
    durationMin: 30,
    type: 'Craft',
    materials: ['Karton', 'Kalem', 'Makas', 'Raptiye'],
    steps: [
      'Çocuk daire keser.',
      '12 sayı yazar etrafına.',
      '2 ok keser (akrep + yelkovan).',
      'Raptiye ile saatin ortasına tutturur.',
      'Sınıf çiftler hâlinde: bir saat söyler, diğeri ayarlar.',
    ],
    variations: 'Dijital format: çocuk "5:30" yazar, diğeri analog saati ayarlar.',
    teacherNote: 'El becerisi + sayı + saat üçü birden. Kalıcılık çok yüksek.',
    seoKeywords: ['karton saat', 'time telling craft', 'saat öğrenme ingilizce', 'clock yapma etkinlik'],
  },
  {
    id: 'transportation-map-route',
    titleTr: 'Ulaşım Haritası Çizimi',
    titleEn: 'Transportation Map Route',
    shortDesc: 'Çocuk evden okula nasıl gittiğini harita üzerinde çizer + İngilizce anlatır.',
    topicIds: ['transportation', 'directions', 'in-the-city'],
    gradeLevels: [4],
    durationMin: 25,
    type: 'Drawing',
    materials: ['A4 kâğıt', 'renkli kalem'],
    steps: [
      'Çocuk kâğıdın sol altına ev çizer.',
      'Sağ üste okul çizer.',
      'Aradaki yolu çizer.',
      'Ulaşım aracını işaretler: car, bus, on foot.',
      'Sınıfa anlatır: "I go to school by bus. First I walk to the bus stop..."',
    ],
    variations: 'Hayalî harita: "Imaginary city" — çocuk kendi hayal şehrini çizer.',
    teacherNote: 'Ulaşım + yön + şehir kelimeleri birleşir. Gerçek hayata bağlanma çok güçlü.',
    seoKeywords: ['ulaşım haritası', 'transportation map', 'go to school by bus', 'evden okula ingilizce'],
  },
  {
    id: 'job-interview-roleplay',
    titleTr: 'Hayalî Meslek Mülakatı',
    titleEn: 'Imaginary Job Interview',
    shortDesc: 'Çocuk bir meslek seçer, diğer çocuk "mülakatçı" olur, basit sorularla konuşma yapar.',
    topicIds: ['jobs', 'simple-questions', 'can-cant'],
    gradeLevels: [4],
    durationMin: 20,
    type: 'RolePlay',
    materials: ['Yok'],
    steps: [
      'Çiftler oluştur.',
      'Bir çocuk meslek seçer (gizli).',
      'Diğeri sorar: "Do you work with people?" "Can you fly?"',
      'Cevap: yes/no.',
      'Mülakatçı tahmin eder.',
    ],
    variations: '"20 questions" oyununun meslek versiyonu.',
    teacherNote: 'Soru sorma kalıpları (can, do, are) pekişir. Çocuk hem konuşur hem dinler.',
    seoKeywords: ['meslek mülakatı', 'job interview ingilizce', 'what do you do', 'jobs etkinlik'],
  },
  {
    id: 'vacation-postcard',
    titleTr: 'Tatil Kartpostalı Yazma',
    titleEn: 'Vacation Postcard Writing',
    shortDesc: 'Çocuk hayalî bir tatil yerinden kartpostal yazar. Hava durumu, aktivite, hisler.',
    topicIds: ['vacation', 'weather', 'feelings', 'food'],
    gradeLevels: [4],
    durationMin: 25,
    type: 'Worksheet',
    materials: ['A6 kâğıt (kartpostal boyutu)', 'kalem'],
    steps: [
      'Çocuk bir tatil yeri hayal eder: deniz, dağ, şehir.',
      'Kartpostalın bir yüzüne resim çizer.',
      'Arka yüze yazar: "Hi Mum! I am in Antalya. The weather is sunny. I swim every day. I eat ice cream. Love, Defne."',
      'Sınıfta okur.',
    ],
    variations: 'Gerçek kartpostal: Çocuk gerçek bir tatil sonrası yazar.',
    teacherNote: 'Tatil + hava + yiyecek + duygu birleşir. Kompoze yazma pratiği.',
    seoKeywords: ['kartpostal yazma', 'postcard writing', 'tatil ingilizce', 'vacation etkinlik'],
  },
  {
    id: 'phonics-letter-sound',
    titleTr: 'Phonics Harf-Ses Kartları',
    titleEn: 'Phonics Letter-Sound Cards',
    shortDesc: 'Çocuğa harf gösterilir, çocuk o harfin sesini söyler ve örnek bir kelime üretir.',
    topicIds: ['classroom-actions', 'school-items'],
    gradeLevels: [1, 2, 3],
    durationMin: 15,
    type: 'Game',
    materials: ['Harf kartları (A-Z)'],
    steps: [
      'Öğretmen harf kartı gösterir: "A"',
      'Çocuk: "/æ/ — Apple!"',
      'Sonraki: "B"',
      '"/b/ — Ball!"',
      '26 harfi yarım grup tamamlar.',
    ],
    variations: 'Hızlı tur: 1 dakikada kim kaç harf tamamlar?',
    teacherNote: 'Phonics, İngilizce okumanın temelidir. Haftada 2-3 kez tekrar ile harfler oturur.',
    seoKeywords: ['phonics ingilizce', 'harf ses kartları', 'A is for apple', 'okuma öğretim'],
  },
  {
    id: 'birthday-month-circle',
    titleTr: 'Doğum Günü Ayı Çemberi',
    titleEn: 'Birthday Month Circle',
    shortDesc: 'Sınıf 12 aya bölünür, her çocuk kendi doğum ayına geçer.',
    topicIds: ['months', 'ordinal-numbers', 'feelings'],
    gradeLevels: [4],
    durationMin: 10,
    type: 'Game',
    materials: ['12 ay etiketi (yere)'],
    steps: [
      'Yere 12 ay etiketini daire şeklinde yerleştir.',
      'Öğretmen: "Go to your birthday month!"',
      'Çocuklar uygun yere gider.',
      'Her grup birlikte söyler: "Our birthday is in May!"',
      'Tek doğum günlü ay varsa o çocuk öne çıkar.',
    ],
    variations: 'Aylar + sıra sayısı: "May is the fifth month."',
    teacherNote: 'Aylar + sosyal etkileşim + sayı pekişir. Sınıfta birlik hissi.',
    seoKeywords: ['doğum günü ayı', 'birthday months', 'my birthday is in', 'months etkinlik'],
  },
  {
    id: 'opposites-board-clap',
    titleTr: 'Zıt Anlamlı Alkış Oyunu',
    titleEn: 'Opposites Clap Game',
    shortDesc: 'Öğretmen bir sıfat söyler, çocuk zıttını söyleyip alkışlar.',
    topicIds: ['opposites', 'adjectives'],
    gradeLevels: [2, 3, 4],
    durationMin: 10,
    type: 'TPR',
    materials: ['Yok'],
    steps: [
      'Sınıfın önünde dur.',
      '"Big!" — çocuklar "Small!" der + 1 alkış.',
      '"Hot!" — "Cold!" + 1 alkış.',
      '"Happy!" — "Sad!" + 1 alkış.',
      'Hız git gide artar.',
    ],
    variations: 'Yanlış cevap veren çocuk oturur. Son kalan kazanır.',
    teacherNote: 'Beden + dil + ritm pekişir. 10 dakikada çocuk 30 zıt çift söyler.',
    seoKeywords: ['zıt anlamlı oyun', 'opposites game', 'big small clap', 'opposites etkinlik'],
  },
]

export function findActivity(id: string): Activity | undefined {
  return activities.find((a) => a.id === id)
}

export function activitiesForTopic(topicId: string): Activity[] {
  return activities.filter((a) => a.topicIds.includes(topicId))
}
